language: python

python:
  - 3.6

install:
  - pip install codecov coverage flake8
  - python setup.py install

script:
  - coverage run --source=destructify --branch -m unittest
#  - flake8 --ignore=W801,E128,E501,W402 destructify

after_success:
  - coverage report
  - codecov
